name: PHPStan

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: CosmoCraft-Team/PharBuilder
          token: ${{ secrets.CC_TOKEN }}
          path: vendor/PharBuilder
      - name: Build
        run: |
          echo Building...
          chmod +x vendor/PharBuilder/BuildScript.php
          php -dphar.readonly=0 vendor/PharBuilder/BuildScript.php --make "" --out vendor/PharBuilder/Warps_V1.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: Warps
          path: vendor/PharBuilder/Warps_V1.phar

  prepare-release:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'
    steps:
      - uses: actions/checkout@v2

      - name: Restore release caches
        uses: actions/download-artifact@v2

      - name: Create and Publish Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Official version"
          prerelease: false
          files: |
            vendor/PharBuilder/Warps_V1.phar