name: PHPStan

on: push

jobs:

  phpstan:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'
    steps:
      - name: Startup
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.

      - name: wget PocketMine-MP
        uses: wei/wget@v1
        with:
          args: -O vendor/PocketMine-MP.phar https://github.com/pmmp/PocketMine-MP/releases/latest/download/PocketMine-MP.phar

      - name: Run PHPStan
        uses: larryTheCoder/pmmp-phpstan-action@master
        with:
          phpstan-config: phpstan.neon.dist

  build:
    name: Phar building
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: CosmoCraft-Team/PharBuilder
          token: ${{ secrets.CC_TOKEN }}
          path: vendor/PharBuilder
      - name: Build
        run: |
          echo Building...
          chmod +x vendor/PharBuilder/BuildScript.php
          php -dphar.readonly=0 vendor/PharBuilder/BuildScript.php --make "" --out vendor/PharBuilder/Warps_V1.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: Builder
          path: vendor/PharBuilder/Warps_V1.phar